# Optimized Release Workflow for Electron App
# Builds, lints, type-checks, packages, and uploads release assets on all major OSes

name: Release App

on:
    release:
        types: [created]

jobs:
    build-and-release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm install

            - name: Lint code
              run: npm run lint

            - name: Type check (frontend)
              run: npx tsc --noEmit -p tsconfig.app.json

            - name: Type check (electron)
              run: npx tsc --noEmit -p src/electron/tsconfig.json

            - name: Build Electron app
              run: npm run build

            - name: Package app (electron-builder)
              run: npm run dist:${{ matrix.os == 'macos-latest' && 'mac' || matrix.os == 'windows-latest' && 'win' || 'linux' }}

            - name: Upload release assets
              uses: softprops/action-gh-release@v2
              with:
                  files: dist-electron/**
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
