name: Security Audit

on:
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level=moderate
    
    - name: Check for known vulnerabilities
      run: |
        if npm audit --audit-level=high --json | jq '.metadata.vulnerabilities.high + .metadata.vulnerabilities.critical > 0' | grep -q true; then
          echo "High or critical vulnerabilities found!"
          npm audit --audit-level=high
          exit 1
        else
          echo "No high or critical vulnerabilities found."
        fi
