name: Test Build

run-name: "Test Build: ${{ github.event.inputs.platform }} (${{ github.event.inputs.build_type }})"

on:
    workflow_dispatch:
        inputs:
            platform:
                description: "Platform to build"
                required: true
                default: "mac"
                type: choice
                options:
                    - mac
                    - linux
                    - win
                    - all
            build_type:
                description: "Build type"
                required: true
                default: "unpacked"
                type: choice
                options:
                    - unpacked
                    - installer

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Set matrix based on platform selection
              id: set-matrix
              run: |
                  if [ "${{ github.event.inputs.platform }}" = "all" ]; then
                    echo 'matrix={"include":[{"os":"macos-latest","platform":"mac"},{"os":"ubuntu-latest","platform":"linux"},{"os":"windows-latest","platform":"win"}]}' >> $GITHUB_OUTPUT
                  elif [ "${{ github.event.inputs.platform }}" = "mac" ]; then
                    echo 'matrix={"include":[{"os":"macos-latest","platform":"mac"}]}' >> $GITHUB_OUTPUT
                  elif [ "${{ github.event.inputs.platform }}" = "linux" ]; then
                    echo 'matrix={"include":[{"os":"ubuntu-latest","platform":"linux"}]}' >> $GITHUB_OUTPUT
                  elif [ "${{ github.event.inputs.platform }}" = "win" ]; then
                    echo 'matrix={"include":[{"os":"windows-latest","platform":"win"}]}' >> $GITHUB_OUTPUT
                  fi
              shell: bash

    test-build:
        needs: setup
        runs-on: ${{ matrix.os }}

        strategy:
            matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build app
              run: |
                  if [ "${{ github.event.inputs.build_type }}" = "unpacked" ]; then
                    npm run test:${{ matrix.platform }}
                  else
                    npm run dist:${{ matrix.platform }}
                  fi
              shell: bash

            - name: Upload unpacked build (macOS .app)
              if: matrix.platform == 'mac' && github.event.inputs.build_type == 'unpacked'
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.inputs.build_type }}-build-macos-app
                  path: dist/mac/*.app
                  retention-days: 30

            - name: Upload installer build (macOS .dmg)
              if: matrix.platform == 'mac' && github.event.inputs.build_type == 'installer'
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.inputs.build_type }}-build-macos-dmg
                  path: dist/*.dmg
                  retention-days: 30

            - name: Upload unpacked build (Linux)
              if: matrix.platform == 'linux' && github.event.inputs.build_type == 'unpacked'
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.inputs.build_type }}-build-linux
                  path: dist/linux-unpacked/
                  retention-days: 30

            - name: Upload installer build (Linux)
              if: matrix.platform == 'linux' && github.event.inputs.build_type == 'installer'
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.inputs.build_type }}-build-linux
                  path: dist/*.AppImage
                  retention-days: 30

            - name: Upload unpacked build (Windows)
              if: matrix.platform == 'win' && github.event.inputs.build_type == 'unpacked'
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.inputs.build_type }}-build-windows
                  path: dist/win-unpacked/
                  retention-days: 30

            - name: Upload installer build (Windows)
              if: matrix.platform == 'win' && github.event.inputs.build_type == 'installer'
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.inputs.build_type }}-build-windows
                  path: |
                      dist/*.exe
                      dist/*.msi
                  retention-days: 30
