name: Test Build

run-name: "Test Build: ${{ github.event.inputs.platform }} (${{ github.event.inputs.build_type }})"

on:
    workflow_dispatch:
        inputs:
            platform:
                description: "Platform"
                required: true
                type: choice
                options:
                    - mac
                    - linux
                    - win
                    - all
            build_type:
                description: "Build type"
                required: true
                default: "unpacked"
                type: choice
                options:
                    - unpacked
                    - installer

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Set matrix based on platform selection
              id: set-matrix
              run: |
                  case "${{ github.event.inputs.platform }}" in
                    "all")
                      echo 'matrix={"include":[{"os":"macos-latest","platform":"mac"},{"os":"ubuntu-latest","platform":"linux"},{"os":"windows-latest","platform":"win"}]}' >> $GITHUB_OUTPUT
                      ;;
                    "mac")
                      echo 'matrix={"include":[{"os":"macos-latest","platform":"mac"}]}' >> $GITHUB_OUTPUT
                      ;;
                    "linux")
                      echo 'matrix={"include":[{"os":"ubuntu-latest","platform":"linux"}]}' >> $GITHUB_OUTPUT
                      ;;
                    "win")
                      echo 'matrix={"include":[{"os":"windows-latest","platform":"win"}]}' >> $GITHUB_OUTPUT
                      ;;
                    *)
                      echo "Error: Invalid platform '${{ github.event.inputs.platform }}'"
                      exit 1
                      ;;
                  esac
              shell: bash

    test-build:
        needs: setup
        runs-on: ${{ matrix.os }}

        strategy:
            matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build app
              run: |
                  case "${{ github.event.inputs.build_type }}" in
                    "unpacked")
                      npm run test:${{ matrix.platform }}
                      ;;
                    "installer")
                      npm run test-installer:${{ matrix.platform }}
                      ;;
                    *)
                      echo "Error: Invalid build type '${{ github.event.inputs.build_type }}'"
                      exit 1
                      ;;
                  esac
              shell: bash

            - name: Debug - List dist directory contents
              if: matrix.platform == 'mac' && github.event.inputs.build_type == 'unpacked'
              run: |
                  echo "=== Contents of dist directory ==="
                  find dist -name "*.app" -type d 2>/dev/null || echo "No .app bundles found"
                  echo "=== Full dist structure ==="
                  ls -la dist/ || echo "dist directory not found"
                  echo "=== Recursive listing ==="
                  find dist -type d -name "*mac*" 2>/dev/null || echo "No mac directories found"
              shell: bash

            - name: Upload unpacked build (macOS)
              if: matrix.platform == 'mac' && github.event.inputs.build_type == 'unpacked'
              uses: actions/upload-artifact@v4
              with:
                  name: unpacked-build-macos-app
                  path: dist/mac-universal/
                  retention-days: 7
                  if-no-files-found: error

            - name: Upload installer build (macOS)
              if: matrix.platform == 'mac' && github.event.inputs.build_type == 'installer'
              uses: actions/upload-artifact@v4
              with:
                  name: installer-build-macos-dmg
                  path: dist/*.dmg
                  retention-days: 7
                  if-no-files-found: error

            - name: Upload unpacked build (Linux)
              if: matrix.platform == 'linux' && github.event.inputs.build_type == 'unpacked'
              uses: actions/upload-artifact@v4
              with:
                  name: unpacked-build-linux
                  path: dist/linux-unpacked/
                  retention-days: 7
                  if-no-files-found: error

            - name: Upload installer build (Linux)
              if: matrix.platform == 'linux' && github.event.inputs.build_type == 'installer'
              uses: actions/upload-artifact@v4
              with:
                  name: installer-build-linux
                  path: dist/*.AppImage
                  retention-days: 7
                  if-no-files-found: error

            - name: Upload unpacked build (Windows)
              if: matrix.platform == 'win' && github.event.inputs.build_type == 'unpacked'
              uses: actions/upload-artifact@v4
              with:
                  name: unpacked-build-windows
                  path: dist/win-unpacked/
                  retention-days: 7
                  if-no-files-found: error

            - name: Upload installer build (Windows)
              if: matrix.platform == 'win' && github.event.inputs.build_type == 'installer'
              uses: actions/upload-artifact@v4
              with:
                  name: installer-build-windows
                  path: dist/*.exe
                  retention-days: 7
                  if-no-files-found: error
